---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcd-infra-node-exporter-scc
  labels:
    app: etcd-infra
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - node-exporter
    verbs:
      - use
