---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Cluster-wide default deny. Apply once per cluster:
#   oc apply -k ./baseline-admin-network-policy/base

resources:
  - baseline-admin-network-policy.yaml
