---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Copy this directory into your application repo, set namespace
# to your project, and apply it with your workloads:
#   oc apply -k ./egress-firewall

# Change this to your project name.
namespace: my-app

resources:
  - egress-firewall.yaml
